name: Format/Lint Code
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn install
          yarn format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: format/lint code
